name: Run Jest Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
    jest-test-for-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'

            - name: Install npm dependencies
              run: npm install

            - name: Run Jest Test
              run: npx jest test.spec.ts
